### ISSUE TITLE
K8s Cluster - No Image match Error

### ISSUE THREAD

**Issue by utianayuba** [BiznetGIO/neo-cli#115]
Hi,

This is my neo.yml

```
clusters:
  kubernetes:
    parameters:
      master_flavor: SM8.4
      master_size: 1
      private_network: net-private1
      worker_flavor: SM4.2
      worker_size: 2
    template: kubernetes
deploy:
- clusters.kubernetes
```
and when creating the cluster, the process is stop with error:

```
ERROR: Property error: : resources.controller.properties.image: : Error validating value '16f795e6-aa68-4b49-a318-d6de8d1bd8aa': No images matching {'name': u'16f795e6-aa68-4b49-a318-d6de8d1bd8aa'}.
```

I need your suggestions.

Thanks
