### ISSUE TITLE
k8s is not deployed on the cluster

### ISSUE THREAD

**Issue by muhammadhanif** [BiznetGIO/neo-cli#122]
I have deployed kubernetes cluster using this neo.yml:

```
clusters:
  hnf-k8s:
    parameters:
      master_flavor: SS2.2
      master_size: 1
      private_network: k8s-network
      worker_flavor: SS2.2
      worker_size: 1
    template: kubernetes
deploy:
- clusters.hnf-k8s
```
I check status of `hnf-k8s` stack is `Create Complete`. There are 3 running instances (controller, master, & worker). I access to controller instance and execute `kube-token`, the result is:

```
[k8s@hnf-k8s-controller-hs422syzowzr ~]$ kube-token 
/usr/bin/kube-token: line 2: kubectl: command not found
/usr/bin/kube-token: line 2: kubectl: command not found
[k8s@hnf-k8s-controller-hs422syzowzr ~]$
```

I think kubernetes is failed deployed on the nodes. I am waiting for the solution. Thank you.

Version of neo-cli:
```
0.7.5
```
